# Generated by Django 4.2.4 on 2023-08-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animdleuser",
            name="user_browser_id",
            field=models.CharField(
                default="8941bd6484303524f28df9f5ed575884",
                max_length=32,
                verbose_name="User Browser ID",
            ),
        ),
    ]
