# Generated by Django 4.2.4 on 2023-08-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="synonyms",
            field=models.CharField(max_length=1000),
        ),
    ]
