# Generated by Django 4.2.4 on 2023-08-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animdleuser",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="animdleuser",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="animdleuser",
            name="user_browser_id",
            field=models.CharField(
                default="", max_length=100, verbose_name="User Browser ID"
            ),
        ),
    ]
