# Generated by Django 4.2.4 on 2023-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_anime_synonyms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="image_url",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="theme",
            name="video_url",
            field=models.CharField(max_length=200),
        ),
    ]
