# Generated by Django 4.2.4 on 2023-08-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_animdleuser_user_browser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animdleuser",
            name="user_browser_id",
            field=models.CharField(
                default="cbfc8c04475edcc138cba0059f91c0b9",
                max_length=32,
                verbose_name="User Browser ID",
            ),
        ),
    ]
