# Generated by Django 4.2.4 on 2023-08-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_animdleuser_user_browser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="animdleuser",
            name="guest",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="animdleuser",
            name="user_browser_id",
            field=models.CharField(
                default="b23702e1f4bfed4d9c89fb888593e0d5",
                max_length=32,
                verbose_name="User Browser ID",
            ),
        ),
    ]
