# Generated by Django 4.2.4 on 2023-08-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_anime_image_url_alter_theme_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
