# Generated by Django 4.2.5 on 2023-09-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_animdleuser_guest_alter_animdleuser_user_browser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animdleuser',
            name='user_browser_id',
            field=models.CharField(default='2bcac2672d8438afe41e775f506ad510', max_length=32, verbose_name='User Browser ID'),
        ),
    ]
