# Generated by Django 4.2.4 on 2023-08-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_anime_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="hardcore_ending",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hardcore_ending",
                to="api.theme",
            ),
        ),
    ]
