# Generated by Django 4.2.4 on 2023-08-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_result_won_result_game_mode_result_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animdleuser",
            name="user_browser_id",
            field=models.CharField(
                default="3e833767338523cdcc8dda782439d660",
                max_length=32,
                verbose_name="User Browser ID",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="type",
            field=models.CharField(choices=[("OP", "OP"), ("ED", "ED")], max_length=2),
        ),
    ]
